export const SUBMIT_RFP = 'SUBMIT_RFP';
export const SUBMIT_RFP_SUCCESS = 'SUBMIT_RFP_SUCCESS';
export const SUBMIT_RFP_FAILURE = 'SUBMIT_RFP_FAILURE';

export const FETCH_COMPONENTS = 'FETCH_COMPONENTS';
export const FETCH_COMPONENTS_SUCCESS = 'FETCH_COMPONENTS_SUCCESS';
export const FETCH_COMPONENTS_FAILURE = 'FETCH_COMPONENTS_FAILURE';

export const FETCH_AUCTIONS = 'FETCH_AUCTIONS';
export const FETCH_AUCTIONS_SUCCESS = 'FETCH_AUCTIONS_SUCCESS';
export const FETCH_AUCTIONS_FAILURE = 'FETCH_AUCTIONS_FAILURE';

export const FETCH_USER_DETAILS = 'FETCH_USER_DETAILS';
export const FETCH_USER_DETAILS_SUCCESS = 'FETCH_USER_DETAILS_SUCCESS';
export const FETCH_USER_DETAILS_FAILURE = 'FETCH_USER_DETAILS_FAILURE';

export const SUBMIT_PURCHASE_ORDER = 'SUBMIT_PURCHASE_ORDER';
export const SUBMIT_PURCHASE_ORDER_SUCCESS = 'SUBMIT_PURCHASE_ORDER_SUCCESS';
export const SUBMIT_PURCHASE_ORDER_FAILURE = 'SUBMIT_PURCHASE_ORDER_FAILURE';
