export const SUBMIT_RFP = 'SUBMIT_RFP';
export const SUBMIT_RFP_SUCCESS = 'SUBMIT_RFP_SUCCESS';
export const SUBMIT_RFP_FAILURE = 'SUBMIT_RFP_FAILURE';
export const FETCH_QUOTES = 'FETCH_QUOTES';
export const FETCH_QUOTES_SUCCESS = 'FETCH_QUOTES_SUCCESS';
export const FETCH_QUOTES_FAILURE = 'FETCH_QUOTES_FAILURE';